"""
dsc_register_fixture_library.py
================================
Robot Framework library for loading, writing, and querying register card
YAML fixture files.

Provides two operating modes for register card test data:
  • Known-data mode  : fixture YAML already contains expected data → normal test run
  • First-run mode   : fixture is (re-)generated by capturing live dialog data

Requires: PyYAML >= 6.0  (pip install PyYAML)

Robot keyword mapping (underscore → space):
  load_register_fixture        → Load Register Fixture
  fixture_exists               → Fixture Exists
  is_first_run_completed       → Is First Run Completed
  get_register_name            → Get Register Name
  get_register_tag             → Get Register Tag
  get_expected_sender          → Get Expected Sender
  is_sender_assertion_enabled  → Is Sender Assertion Enabled
  get_data_fields_to_verify    → Get Data Fields To Verify
  get_pdf_configuration        → Get Pdf Configuration
  build_first_run_fixture      → Build First Run Fixture
  write_register_fixture       → Write Register Fixture
"""

import pathlib
import re
from datetime import datetime

import yaml


class dsc_register_fixture_library:
    """Robot Framework library for register card YAML fixture management."""

    ROBOT_LIBRARY_SCOPE = "SUITE"

    def _field_key_matches(self, actual_key: str, expected_key: str) -> bool:
        """Match exact keys first, then tolerate captured section-prefix joins."""
        actual = " ".join(str(actual_key).split())
        expected = " ".join(str(expected_key).split())
        if not actual or not expected:
            return False
        if actual == expected:
            return True
        actual_compact = actual.replace(" ", "")
        expected_compact = expected.replace(" ", "")
        return expected_compact in actual_compact

    def _compact_text(self, text: str) -> str:
        """Normalize dialog text for resilient substring comparisons."""
        return re.sub(r"\s+", "", str(text or "")).replace(":", "")

    # ── Loading ────────────────────────────────────────────────────────────────

    def load_register_fixture(self, fixture_path: str) -> dict:
        """
        Load a register card fixture YAML file and return its content as a dict.

        Raises FileNotFoundError if the file does not exist; the error message
        includes the first-run command to generate the fixture.
        """
        path = pathlib.Path(fixture_path)
        if not path.exists():
            raise FileNotFoundError(
                f"Register fixture not found: {fixture_path}\n"
                "Run the first-run test to generate it:\n"
                "  robot --include first-run "
                "tests/ui/ts_05_smoke_test_register_cards_generic.robot"
            )
        with open(path, encoding="utf-8") as fh:
            return yaml.safe_load(fh)

    def fixture_exists(self, fixture_path: str) -> bool:
        """Return True if the fixture file exists on disk, False otherwise."""
        return pathlib.Path(fixture_path).exists()

    # ── Accessors ──────────────────────────────────────────────────────────────

    def is_first_run_completed(self, fixture: dict) -> bool:
        """
        Return True if the fixture was successfully populated by a first-run.
        Reads fixture['first_run']['completed'].
        """
        return bool(fixture.get("first_run", {}).get("completed", False))

    def get_register_name(self, fixture: dict) -> str:
        """Return the register card name (h3 heading text) from the fixture."""
        return fixture.get("register", {}).get("name", "")

    def get_register_tag(self, fixture: dict) -> str:
        """Return the short tag string (e.g. 'bva') from the fixture."""
        return fixture.get("register", {}).get("tag", "")

    def get_expected_sender(self, fixture: dict) -> str:
        """Return the expected sender organisation text from the fixture."""
        return fixture.get("dialog", {}).get("sender", "")

    def is_sender_assertion_enabled(self, fixture: dict) -> bool:
        """
        Return True if the fixture's assert_sender flag is set (default: True).
        When True, the dialog sender text must be visible during verification.
        """
        return bool(fixture.get("dialog", {}).get("assert_sender", True))

    def get_data_fields_to_verify(self, fixture: dict) -> list:
        """
        Return the list of data field dicts from the fixture.

        Each dict contains:
          key          (str)  – visible label text in the dialog
          value        (str)  – expected value text
          assert_value (bool) – if True, verify value visibility; if False, key only
        """
        return fixture.get("dialog", {}).get("data_fields", [])

    def get_pdf_configuration(self, fixture: dict) -> dict:
        """
        Return the pdf configuration dictionary from the fixture.
        Contains 'verify', 'filename_pattern', etc.
        """
        default_pdf = {
            "verify": False,
            "filename_pattern": (
                r"^Datenschutzcockpit-\d{2}_\d{2}_\d{4}-\d{2}_\d{2}_uhr\.pdf$"
            ),
        }
        return fixture.get("pdf", default_pdf)

    def has_data_field_key(self, data_fields: list, key: str) -> bool:
        """Return True when captured dialog data contains the exact key."""
        expected_key = str(key).strip()
        for field in data_fields or []:
            if not isinstance(field, dict):
                continue
            if self._field_key_matches(field.get("key", ""), expected_key):
                return True
        return False

    def get_data_field_value(self, data_fields: list, key: str) -> str:
        """Return the value paired with the given key from captured dialog data."""
        expected_key = str(key).strip()
        for field in data_fields or []:
            if not isinstance(field, dict):
                continue
            if self._field_key_matches(field.get("key", ""), expected_key):
                value = str(field.get("value", "")).strip()
                if expected_key:
                    value = re.sub(rf"^{re.escape(expected_key)}\s*", "", value)
                return value.strip()
        return ""

    def dialog_contains_field_key(self, dialog_text: str, key: str) -> bool:
        """Return True when the normalized dialog text contains the expected key."""
        return self._compact_text(key) in self._compact_text(dialog_text)

    def dialog_contains_field_pair(self, dialog_text: str, key: str, value: str) -> bool:
        """Return True when the normalized dialog text contains key followed by value."""
        expected_sequence = self._compact_text(key) + self._compact_text(value)
        return expected_sequence in self._compact_text(dialog_text)

    # ── Writing (first-run) ────────────────────────────────────────────────────

    def build_first_run_fixture(
        self,
        register_name: str,
        register_tag: str,
        sender: str,
        data_fields: list,
        existing_fixture: dict = None,
    ) -> dict:
        """
        Build a complete fixture dict from data captured during a first-run.

        Arguments:
          register_name    – exact h3 text of the register card
          register_tag     – short identifier (e.g. 'bva')
          sender           – captured sender organisation text
          data_fields      – list of dicts with 'key' and 'value' keys
          existing_fixture – if provided, its 'pdf' section is preserved

        All captured fields receive assert_value=True (values confirmed live).
        Empty keys are filtered out automatically.
        """
        fields = []
        for field in data_fields:
            if isinstance(field, dict):
                key = str(field.get("key", "")).strip()
                value = str(field.get("value", "")).strip()
                if key:
                    fields.append(
                        {
                            "key": key,
                            "value": value,
                            "assert_value": True,
                        }
                    )

        # Preserve pdf section from an existing fixture when available
        default_pdf = {
            "verify": False,
            "filename_pattern": (
                r"^Datenschutzcockpit-\d{2}_\d{2}_\d{4}-\d{2}_\d{2}_uhr\.pdf$"
            ),
        }
        pdf_section = (
            existing_fixture.get("pdf", default_pdf)
            if existing_fixture
            else default_pdf
        )

        return {
            "register": {
                "name": str(register_name),
                "tag": str(register_tag),
            },
            "first_run": {
                "completed": True,
                "captured_at": datetime.now().strftime("%Y-%m-%dT%H:%M:%S"),
            },
            "dialog": {
                "sender": str(sender).strip(),
                "assert_sender": True,
                "data_fields": fields,
            },
            "pdf": pdf_section,
        }

    def write_register_fixture(self, fixture_path: str, fixture_data: dict) -> None:
        """
        Write a register fixture dict to the given YAML file.

        Creates parent directories if they do not exist.
        Unicode characters (German umlauts, etc.) are written as-is.
        """
        path = pathlib.Path(fixture_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            yaml.dump(
                fixture_data,
                fh,
                allow_unicode=True,
                default_flow_style=False,
                sort_keys=False,
                indent=2,
            )
