name: Robot Framework (Self-hosted)

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'        # your current working branch    
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start AusweisApp
        run: |
          docker compose -f Playwright_RobotF_311/docker2/docker-compose.tests.yml up -d

      - name: Run Tests
        run: |
          docker run --rm \
            --network host \
            -v ${{ github.workspace }}/results:/app/results \
            robot-tests \
            robot \
              --variable CI:True \
              --variable HEADLESS:True \
              --variable BASE_URL:https://datenschutzcockpit.bund.de/spa/ \
              --variable BROWSER:chromium \
              --outputdir results \
              tests/

      - name: Stop AusweisApp
        if: always()
        run: |
          docker compose -f Playwright_RobotF_311/docker2/docker-compose.tests.yml down

      - name: Upload Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: results
          path: results/