name: docker-sdk-tests-02

services:
  ausweisapp-sdk:
    image: ausweisapp-sdk:latest
    build:
      context: ../..
      dockerfile: docker/common/ausweisapp-sdk.Dockerfile

    ports:
      - "24727:24727"

    restart: "no"